
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef BM_NODE_H
#define BM_NODE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 bm_node_valueRangeTest (UNS8 typeValue, void * value);
const CONSTSTORE indextable * bm_node_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data bm_node_Data;

#endif // BM_NODE_H
